global:
  azure:
    billingIdentifier: DONOTMODIFY
    images:
      frontend:
        digest: sha256:3793047f288ef90aae7314aa0be8fd0196f6a9c198814bff7322ac19ae0ad0dc
        image: todojs
        registry: msalem2022.azurecr.io









